添加运维相关程序和文档
jenkins-zh/application-operation pull request #2
Opened 2020-04-11 05:13 UTC by anxk

晚上回来我先核对一下

2020-04-11 10:20 UTC, LinuxSuRen requested changes
感谢提供运维相关的内容。
.idea 目录通常不会提交，可以加到 `.gitignore` 中

2020-04-11 10:20 UTC, LinuxSuRen commented on compose/jenkins-nginx.yaml
> +    image: nginx:latest
使用最新版本的话，每次执行都是一个未知的结果。可以选用一个当前最新的稳定版本。

2020-04-11 13:56 UTC, anxk commented on compose/jenkins-nginx.yaml
> +    image: nginx:latest
好的，我把.idea去掉；latest 确实不合适，我去找个版本替换一下。

2020-04-12 01:40 UTC, LinuxSuRen requested changes

2020-04-12 01:40 UTC, LinuxSuRen commented on config/ssh/ssh.yaml
> +hosts:
如果所有人的配置信息都放在一起的话，多人修改同一个文件容易有冲突。ssh 的配置文件是否可以每个人有一个文件呢，文件名是 GitHub ID。

2020-04-12 04:58 UTC, anxk commented on config/ssh/ssh.yaml
> +hosts:
已经修改，会读取 repo/config/ssh/下所有的 *.yaml文件，只要内容符合要求就可以

2020-04-13 14:10 UTC, yJunS reviewed
初始化的rsa配置文件没必要放多个的，只要测试没问题之后，后续添加就可以，而且读取的路径在存放的时候是不是要做改变呢？

2020-04-13 16:21 UTC, anxk commented
> 
> 
> 初始化的rsa配置文件没必要放多个的，只要测试没问题之后，后续添加就可以，而且读取的路径在存放的时候是不是要做改变呢？

是的，只是个示例，有点多，我去掉些。

2020-04-15 00:17 UTC, LinuxSuRen approved these changes

2020-05-04 12:23 UTC, merged